# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyCamera' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyCamera

end

target 'MyCameraSiri' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyCameraSiri

end

target 'MyCameraSiriUI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for MyCameraSiriUI
 pod 'SDWebImage'

end
